### PR TITLE
37 Combine Chemicals and TrueChemicals Web Service

### LINKED ISSUE #37: Combine Chemicals and TrueChemicals Web Service
Combine the chemicals and truechemicals web service, the resulting web service called chemicals with the desired behavior:

`/chemicals/{rid}`  =>   sid, rid, name, cas, datadocument_id
`/chemicals/` => list of chemicals with sid, rid, name, cas, datadocument_id

Consolidate sid and rid into a single field called id

### PR DESCRIPTION
**Pull request by mwfrost**
Closes: #37 

The chemicals endpoint previously used the `dashboard_rawchem.id` field as its lookup key. This changes it to use the RID, where available, instead. EPA confirms that there will be an RID for every RawChem record, and there are no use cases where a user would have the native `RawChem.id` key anyway.

This branch also removes the TrueChemical views. Those endpoints returned lists of distinct values from the RawChem-to-DSSTOXLookup relationship. The views and routes have been moved into `/chemicals/distinct/` with addresses like `/chemicals/distinct/?attribute=true_chemname`.

### CODE REVIEW

**Review by debboutr — COMMENTED** [review]
the `chemicals/distinct/` endpoint is currently failing
```
MultiValueDictKeyError at /chemicals/distinct/
'attribute'
```
you might try using the `.get()` method on `self.request.query_params` where you can add a default or leave None for comparison.

the chemicalsDistinctList section of the docs is a bit confusing to understand to put a URL like `chemicals/distinct/?attribute=sid` or any of the other attrs there are no examples in the docs. Also, the Response section doesn't look consistent with the others, it just lists 200 as a response. 

could these just be endpoints instead of coming in as a parameter? 
```
/chemicals/distinct/cas/
/chemicals/distinct/name/
/chemicals/distinct/sid/
```
this looks good and I think I'm following what you're trying to do here, but there's not a lot of chatter about how all this is supposed to go in tickets or anywhere. Should the default response if a user enters in a non-existent attribute into the URL, say "?attribute=foo" that it should return all? or should it be `detail | "Not found."`? not sure of the standard for this kind of thing

Lastly, the test show you need to run ...
```
$ black .
$ pyflakes .
```

**Comment by debboutr** [comment]
here's a way to remove the duplication in attribute selection using a `dict` and `namedtuples`
```
    import collections
    Attr = collections.namedtuple('Attr', 'query serializer')
    flds = {
            "sid"           : Attr(query="dsstox__sid",
                                serializer=ChemicalSidAggSerializer),
            "true_cas"      : Attr(query="dsstox__true_cas",
                                serializer=ChemicalTrueCasAggSerializer) ,
            "true_chem_name": Attr(query="dsstox__true_chemname",
                                serializer=ChemicalTrueChemNameAggSerializer),
            "true_chemname" : Attr(query="dsstox__true_chemname",
                                serializer=ChemicalTrueChemNameAggSerializer),
            }
    ...
    def get_serializer_class(self):
        q = self.request.query_params.get("attribute","")
        attr = flds.get(q.lower())
        if attr:
            return attr.serializer
        return ChemicalSerializer

    def get_queryset(self):
        q = self.request.query_params.get("attribute","")
        attr = flds.get(q.lower())
        qs = models.RawChem.objects.filter(dsstox__isnull=False)
        if attr:
            return qs.values(attr.query).distinct().order_by(attr.query)
        else:
            return qs
```

**Comment by mwfrost** [comment]
@debboutr Check out the latest. Thanks for the idea above - it works great.

**Review by debboutr — APPROVED** [review]
looks good!

**Pull request merged**
